CREATE DATABASE BANHANG ;
GO
 
	USE BANHANG;
	CREATE TABLE KHACHHANG
	(
		MAKHACHHANG VARCHAR(10) PRIMARY KEY,
		TENCONGTY NVARCHAR(50) NOT NULL,
		TENGIAODICH NVARCHAR(50) NOT NULL,
		DIACHI NVARCHAR(50) NOT NULL,
		EMAIL VARCHAR(20),
		DIENTHOAI CHAR(10),
		FAX NVARCHAR(10)
	)
	GO
	CREATE TABLE DONDATHANG 
	(
		SOHOADON VARCHAR(10) PRIMARY KEY,
		MAKHACHHANG VARCHAR(10) NOT NULL,
		MANHANVIEN VARCHAR(10) NOT NULL,
		NGAYDATHANG DATE NOT NULL,
		NGAYGIAOHANG DATE CHECK(NGAYDATHANG <= NGAYCHUYENHANG),
		NGAYCHUYENHANG DATE CHECK(NGAYCHUYENHANG <= NGAYGIAOHANG),
		NOIGIAOHANG NVARCHAR(50) NOT NULL
	)
	GO
	CREATE TABLE NHANVIEN 
	(
		MANHANVIEN VARCHAR(10)
	)
